// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bd.Models;

public partial class Auto_db
{
    public int auto_db_id { get; set; }

    public string mark { get; set; }

    public string model { get; set; }

    public double? engine_power { get; set; }
    
    public double? fuel_consumption { get; set; }
}